#include "molterm/io/SessionExporter.h"
#include "molterm/render/ColorMapper.h"

#include <algorithm>
#include <cassert>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <ostream>
#include <set>
#include <unordered_map>
#include <vector>

namespace molterm {

// Write current in-memory coordinates as a PDB file for the .pml bundle.
// This captures any transforms (alignment, etc.) applied since loading.
//
// Deliberately separate from the canonical molterm::writePdb (io/PdbWriter.cpp):
// the .pml's show/color/measurement `id` selections require serial ==
// atomIndex+1, but writePdb bumps the serial on every TER record, breaking that
// 1:1 mapping for multi-chain structures. Don't swap this for writePdb without
// threading an atomIndex→serial map through the emitById/measurement sites.
static bool writePDB(const MolObject& obj, const std::string& path) {
    std::ofstream out(path);
    if (!out) return false;

    const auto& atoms = obj.atoms();
    std::string prevChain;

    for (int i = 0; i < static_cast<int>(atoms.size()); ++i) {
        const auto& a = atoms[i];

        // Insert TER between chains
        if (!prevChain.empty() && a.chainId != prevChain) {
            out << "TER\n";
        }
        prevChain = a.chainId;

        // HETATM for ligands/heteroatoms so PyMOL recognizes them as
        // non-polymer (distance-bonds them, honors `resn`/het selections).
        const char* record = a.isHet ? "HETATM" : "ATOM";
        char line[82];
        snprintf(line, sizeof(line),
            "%-6s%5d %-4s %3s %c%4d%c   %8.3f%8.3f%8.3f%6.2f%6.2f          %2s",
            record,
            (i + 1) % 100000,
            a.name.c_str(),
            a.resName.c_str(),
            a.chainId.empty() ? ' ' : a.chainId[0],
            a.resSeq % 10000,
            a.insCode,
            static_cast<double>(a.x),
            static_cast<double>(a.y),
            static_cast<double>(a.z),
            static_cast<double>(a.occupancy),
            static_cast<double>(a.bFactor),
            a.element.c_str());
        out << line << "\n";
    }
    out << "TER\nEND\n";
    return true;
}

// Derive the directory portion of a filepath
static std::string dirOfPath(const std::string& filepath) {
    auto slash = filepath.rfind('/');
    if (slash == std::string::npos) return ".";
    return filepath.substr(0, slash);
}

static constexpr size_t kIdChunk = 200;

// Emit a PyMOL command (`show`/`color`) scoped to specific atoms via 1-based
// `id` lists, chunked so no single selection line grows unwieldy. Serials are
// atomIndex+1 to match writePDB()'s 1..N numbering. `sel` is "id" (additive,
// chunkable) or "not id" (the caller must pass a single chunk — a negation
// doesn't compose across additive `show` lines). `tail` appends an extra
// selector (e.g. " and name CA+C+N+O" for backbone).
static void emitById(std::ostream& out, const char* cmd, const std::string& head,
                     const std::string& obj, const char* sel, const char* tail,
                     const std::vector<int>& serials) {
    // A negated selection can't be chunked — each additive `show … not id <c>`
    // line would re-show everything outside its chunk. Callers pass one chunk.
    assert(serials.size() <= kIdChunk || std::strcmp(sel, "not id") != 0);
    for (size_t s = 0; s < serials.size(); s += kIdChunk) {
        size_t e = std::min(s + kIdChunk, serials.size());
        out << cmd << " " << head << ", " << obj << " and " << sel << " ";
        for (size_t i = s; i < e; ++i) out << (i > s ? "+" : "") << serials[i];
        out << tail << "\n";
    }
}

std::string SessionExporter::exportPML(const std::string& filepath, const Tab& tab,
                                       int /*viewportW*/, int /*viewportH*/,
                                       StereoMode stereoMode,
                                       float stereoAngle,
                                       const std::vector<Measurement>& measurements) {
    std::ofstream out(filepath);
    if (!out.is_open())
        return "Cannot open file: " + filepath;

    std::string dir = dirOfPath(filepath);

    out << "# Generated by MolTerm\n";
    out << "# Tab: " << tab.name() << "\n\n";

    out << "set auto_zoom, off\n";
    out << "viewport 1280, 960\n";
    if (stereoMode != StereoMode::Off) {
        out << "set stereo_angle, " << stereoAngle << "\n";
        out << "stereo " << (stereoMode == StereoMode::Crosseye ? "crosseye" : "walleye") << "\n";
        out << "stereo on\n";
    }
    out << "\n";

    // Write current coordinates as PDB files alongside the .pml,
    // so aligned/moved objects are faithfully exported.
    for (const auto& obj : tab.objects()) {
        std::string pdbName = obj->name() + ".pdb";
        std::string pdbPath = dir + "/" + pdbName;
        if (!writePDB(*obj, pdbPath)) {
            return "Failed to write " + pdbPath;
        }
        out << "load " << pdbName << ", " << obj->name() << "\n";
    }
    out << "\n";

    // Hide everything first, then selectively show
    out << "hide everything\n";

    for (const auto& obj : tab.objects()) {
        const std::string& name = obj->name();

        if (!obj->visible()) {
            out << "disable " << name << "\n";
            continue;
        }

        // Show active representations — honor per-atom masks (e.g.
        // `show wire ligand`) so ligand-only / selection-scoped reprs survive
        // the export instead of collapsing to the whole object or vanishing.
        // Backbone maps to a CA+C+N+O-restricted cartoon.
        struct PyRepr { ReprType r; const char* name; const char* tail; };
        static const PyRepr kReprs[] = {
            {ReprType::Wireframe, "lines",   ""},
            {ReprType::BallStick, "sticks",  ""},
            {ReprType::Spacefill, "spheres", ""},
            {ReprType::Cartoon,   "cartoon", ""},
            {ReprType::Ribbon,    "cartoon", ""},
            {ReprType::Surface,   "surface", ""},
            {ReprType::Backbone,  "cartoon", " and name CA+C+N+O"},
        };
        const int nAtoms = static_cast<int>(obj->atoms().size());
        for (const auto& pr : kReprs) {
            if (!obj->reprVisible(pr.r)) continue;
            std::vector<int> shown, hidden;  // 1-based serials
            for (int i = 0; i < nAtoms; ++i)
                (obj->reprVisibleForAtom(pr.r, i) ? shown : hidden).push_back(i + 1);
            if (shown.empty()) continue;
            if (hidden.empty())
                out << "show " << pr.name << ", " << name << pr.tail << "\n";
            else if (hidden.size() <= kIdChunk)  // shorter as a one-line complement
                emitById(out, "show", pr.name, name, "not id", pr.tail, hidden);
            else
                emitById(out, "show", pr.name, name, "id", pr.tail, shown);
        }

        // Color scheme (match MolTerm's CPK palette exactly)
        switch (obj->colorScheme()) {
            case ColorScheme::Element:
                // Names sourced from pymolColorName so the CPK palette has a
                // single home (shared with per-atom `color element` overrides).
                out << "color " << pymolColorName(kColorCarbon)     << ", " << name << " and elem C\n";
                out << "color " << pymolColorName(kColorNitrogen)   << ", " << name << " and elem N\n";
                out << "color " << pymolColorName(kColorOxygen)     << ", " << name << " and elem O\n";
                out << "color " << pymolColorName(kColorSulfur)     << ", " << name << " and elem S\n";
                out << "color " << pymolColorName(kColorPhosphorus) << ", " << name << " and elem P\n";
                out << "color " << pymolColorName(kColorHydrogen)   << ", " << name << " and elem H\n";
                out << "color " << pymolColorName(kColorIron)       << ", " << name << " and elem Fe\n";
                out << "color " << pymolColorName(kColorOther)      << ", " << name << " and not (elem C+N+O+S+P+H+Fe)\n";
                break;
            case ColorScheme::Chain: {
                // Match MolTerm's chain color cycle: A=green, B=cyan, C=magenta, D=yellow, E=red, F=blue
                static const char* kChainColors[] = {"green", "cyan", "magenta", "yellow", "red", "blue"};
                // Collect unique chain IDs
                std::set<std::string> chains;
                for (const auto& a : obj->atoms()) chains.insert(a.chainId);
                for (const auto& ch : chains) {
                    int idx = ch.empty() ? 0 : ((ch[0] - 'A') % 6);
                    if (idx < 0) idx = 0;
                    out << "color " << kChainColors[idx] << ", " << name << " and chain " << ch << "\n";
                }
                break;
            }
            case ColorScheme::SecondaryStructure:
                out << "color red, " << name << " and ss H\n";
                out << "color yellow, " << name << " and ss S\n";
                out << "color green, " << name << " and ss L+''\n";
                break;
            case ColorScheme::BFactor:
                out << "spectrum b, blue_green_red, " << name << "\n";
                break;
            case ColorScheme::PLDDT:
                out << "# pLDDT confidence coloring (AlphaFold)\n";
                out << "color 0x0053D6, " << name << " and b > 90  # very high\n";
                out << "color 0x65CBF3, " << name << " and b > 70 and b <= 90  # high\n";
                out << "color 0xFFDB13, " << name << " and b > 50 and b <= 70  # low\n";
                out << "color 0xFF7D45, " << name << " and b <= 50  # very low\n";
                break;
            case ColorScheme::Rainbow:
                out << "spectrum count, blue_cyan_green_yellow_red, " << name << "\n";
                break;
            default:
                break;
        }

        // Per-atom color overrides (e.g. `color element ligand` heteroatoms).
        // Chunked id lists — the old 50-id cap appended a literal "or ..."
        // that PyMOL rejects, silently dropping the rest of a ligand's color.
        const auto& atomColors = obj->atomColors();
        if (!atomColors.empty()) {
            std::unordered_map<int, std::vector<int>> colorGroups;
            for (int i = 0; i < static_cast<int>(atomColors.size()); ++i)
                if (atomColors[i] >= 0)
                    colorGroups[atomColors[i]].push_back(i + 1);  // 1-based serials
            for (const auto& [colorPair, serials] : colorGroups) {
                std::string pymolColor = pymolColorName(colorPair);
                if (pymolColor.empty()) continue;
                emitById(out, "color", pymolColor, name, "id", "", serials);
            }
        }
    }

    out << "\n";

    // Camera / set_view
    // PyMOL set_view 18-float format:
    //   [0-8]:   column-major 3x3 rotation (model axes → camera axes)
    //   [9-11]:  origin of rotation relative to camera (in camera space)
    //   [12-14]: origin of rotation (in model space)
    //   [15]:    front plane distance from camera
    //   [16]:    rear plane distance from camera
    //   [17]:    orthoscopic flag
    //
    // MolTerm's rot_ is row-major 3x3: R*v = [r0 r1 r2; r3 r4 r5; r6 r7 r8] * v
    // PyMOL reads [0-8] as column-major via glm::make_mat4, so:
    //   set_view col j = (view[3j], view[3j+1], view[3j+2])
    // For same rotation, column-major storage = transposed row-major array.
    const auto& cam = tab.camera();
    const auto& r = cam.rotation();
    float cx = cam.centerX(), cy = cam.centerY(), cz = cam.centerZ();

    // set_view installs MolTerm's rotation + center; `zoom` AFTER it fits the
    // scale to the actual molecule. The previous order (zoom before set_view)
    // was a no-op — set_view's distance overwrote the fitted scale, so every
    // export came out at one fixed zoom that cropped larger structures. `zoom`
    // keeps the rotation and only refits distance/clipping; the buffer leaves
    // margin so the molecule isn't edge-tight.
    out << "set orthoscopic, 1\n";
    float dist = 200.0f;  // placeholder; `zoom` below recomputes the real distance

    char buf[1024];
    snprintf(buf, sizeof(buf),
        "set_view (\\\n"
        "  %14.9f, %14.9f, %14.9f,\\\n"
        "  %14.9f, %14.9f, %14.9f,\\\n"
        "  %14.9f, %14.9f, %14.9f,\\\n"
        "  %14.9f, %14.9f, %14.9f,\\\n"
        "  %14.9f, %14.9f, %14.9f,\\\n"
        "  %14.9f, %14.9f, %14.9f )\n",
        r[0], r[3], r[6],
        r[1], r[4], r[7],
        r[2], r[5], r[8],
        0.0f, 0.0f, -dist,
        cx,   cy,    cz,
        50.0f, 500.0f, -1.0f);  // -1 = ortho ON
    out << buf;
    out << "zoom buffer=5\n";  // fit to molecule size with margin (see above)

    // PyMOL `id N` uses PDB serials. Each measurement names its owning object
    // (issue #101); resolve per measurement, falling back to the first object
    // for legacy entries that predate the field.
    if (!measurements.empty() && !tab.objects().empty()) {
        // Escape user caption for PyMOL's "..."-quoted label argument.
        auto escapeLabel = [](const std::string& s) {
            std::string out;
            out.reserve(s.size());
            for (char c : s) {
                if      (c == '\\') out += "\\\\";
                else if (c == '"')  out += "\\\"";
                else if (c == '\n' || c == '\r') out += ' ';
                else                out += c;
            }
            return out;
        };
        auto objByName = [&](const std::string& name) -> std::shared_ptr<MolObject> {
            if (!name.empty())
                for (const auto& o : tab.objects())
                    if (o && o->name() == name) return o;
            return tab.objects().front();
        };
        out << "\n# Persistent annotations from :measure / :angle / :dihedral\n";
        int idx = 1;
        for (const auto& m : measurements) {
            const auto& obj = objByName(m.obj);
            const auto& atoms = obj->atoms();
            const std::string& objName = obj->name();
            std::vector<int> serials;
            bool ok = true;
            for (int aidx : m.atoms) {
                if (aidx < 0 || aidx >= static_cast<int>(atoms.size())) { ok = false; break; }
                serials.push_back(aidx + 1);  // match writePDB()'s 1..N numbering
            }
            if (!ok) continue;
            const char* kind = nullptr;
            if      (m.atoms.size() == 2) kind = "distance";
            else if (m.atoms.size() == 3) kind = "angle";
            else if (m.atoms.size() == 4) kind = "dihedral";
            else continue;
            out << kind << " m" << idx << ", ";
            for (size_t i = 0; i < serials.size(); ++i) {
                if (i) out << ", ";
                out << objName << " and id " << serials[i];
            }
            out << "\n";
            if (!m.caption.empty())
                out << "label m" << idx << ", \"" << escapeLabel(m.caption) << "\"\n";
            ++idx;
        }
    }

    out.close();

    int nObj = static_cast<int>(tab.objects().size());
    return "Exported " + std::to_string(nObj) + " object(s) + .pml to " + dir + "/";
}

std::string SessionExporter::pymolReprName(ReprType r) {
    switch (r) {
        case ReprType::Wireframe: return "lines";
        case ReprType::BallStick: return "sticks";
        case ReprType::Spacefill: return "spheres";
        case ReprType::Cartoon:   return "cartoon";
        case ReprType::Ribbon:    return "ribbon";
        case ReprType::Backbone:  return "cartoon";
        case ReprType::Surface:   return "surface";
    }
    return "lines";
}

std::string SessionExporter::pymolColorScheme(ColorScheme s) {
    switch (s) {
        case ColorScheme::Element:            return "element";
        case ColorScheme::Chain:              return "chain";
        case ColorScheme::SecondaryStructure: return "ss";
        case ColorScheme::BFactor:            return "b";
        case ColorScheme::PLDDT:              return "b";
        default:                              return "";
    }
}

std::string SessionExporter::pymolColorName(int colorPairId) {
    // Hex/rgb literals (issue #79) round-trip as PyMOL `0xRRGGBB` so the
    // exact authored colour shows up in the exported figure script.
    if (isCustomColor(colorPairId)) {
        auto rgb = unpackCustomRGB(colorPairId);
        char buf[16];
        std::snprintf(buf, sizeof(buf), "0x%02X%02X%02X", rgb[0], rgb[1], rgb[2]);
        return buf;
    }
    switch (colorPairId) {
        case kColorRed:     return "red";
        case kColorGreen:   return "green";
        case kColorBlue:    return "blue";
        case kColorYellow:  return "yellow";
        case kColorMagenta: return "magenta";
        case kColorCyan:    return "cyan";
        case kColorWhite:   return "white";
        case kColorOrange:  return "orange";
        case kColorPink:    return "hotpink";
        case kColorLime:    return "lime";
        case kColorTeal:    return "teal";
        case kColorPurple:  return "purple";
        case kColorSalmon:  return "salmon";
        case kColorSlate:   return "slate";
        case kColorGray:    return "gray";
        // Element (CPK) palette — mirrors the per-elem scheme above so
        // `color element` per-atom overrides (e.g. ligand heteroatoms) export.
        case kColorCarbon:     return "green";
        case kColorNitrogen:   return "blue";
        case kColorOxygen:     return "red";
        case kColorSulfur:     return "yellow";
        case kColorPhosphorus: return "magenta";
        case kColorHydrogen:   return "white";
        case kColorIron:       return "cyan";
        case kColorOther:      return "white";
        default:            return "";
    }
}

} // namespace molterm
