#include "molterm/io/SessionExporter.h"
#include "molterm/render/ColorMapper.h"

#include <cstdio>
#include <fstream>
#include <set>
#include <unordered_map>

namespace molterm {

// Write current in-memory coordinates as a PDB file.
// This captures any transforms (alignment, etc.) applied since loading.
static bool writePDB(const MolObject& obj, const std::string& path) {
    std::ofstream out(path);
    if (!out) return false;

    const auto& atoms = obj.atoms();
    std::string prevChain;

    for (int i = 0; i < static_cast<int>(atoms.size()); ++i) {
        const auto& a = atoms[i];

        // Insert TER between chains
        if (!prevChain.empty() && a.chainId != prevChain) {
            out << "TER\n";
        }
        prevChain = a.chainId;

        char line[82];
        snprintf(line, sizeof(line),
            "ATOM  %5d %-4s %3s %c%4d%c   %8.3f%8.3f%8.3f%6.2f%6.2f          %2s",
            (i + 1) % 100000,
            a.name.c_str(),
            a.resName.c_str(),
            a.chainId.empty() ? ' ' : a.chainId[0],
            a.resSeq % 10000,
            a.insCode,
            static_cast<double>(a.x),
            static_cast<double>(a.y),
            static_cast<double>(a.z),
            static_cast<double>(a.occupancy),
            static_cast<double>(a.bFactor),
            a.element.c_str());
        out << line << "\n";
    }
    out << "TER\nEND\n";
    return true;
}

// Derive the directory portion of a filepath
static std::string dirOfPath(const std::string& filepath) {
    auto slash = filepath.rfind('/');
    if (slash == std::string::npos) return ".";
    return filepath.substr(0, slash);
}

std::string SessionExporter::exportPML(const std::string& filepath, const Tab& tab,
                                       int /*viewportW*/, int /*viewportH*/) {
    std::ofstream out(filepath);
    if (!out.is_open())
        return "Cannot open file: " + filepath;

    std::string dir = dirOfPath(filepath);

    out << "# Generated by MolTerm\n";
    out << "# Tab: " << tab.name() << "\n\n";

    out << "set auto_zoom, off\n\n";

    // Write current coordinates as PDB files alongside the .pml,
    // so aligned/moved objects are faithfully exported.
    for (const auto& obj : tab.objects()) {
        std::string pdbName = obj->name() + ".pdb";
        std::string pdbPath = dir + "/" + pdbName;
        if (!writePDB(*obj, pdbPath)) {
            return "Failed to write " + pdbPath;
        }
        out << "load " << pdbName << ", " << obj->name() << "\n";
    }
    out << "\n";

    // Hide everything first, then selectively show
    out << "hide everything\n";

    for (const auto& obj : tab.objects()) {
        const std::string& name = obj->name();

        if (!obj->visible()) {
            out << "disable " << name << "\n";
            continue;
        }

        // Show active representations
        if (obj->reprVisible(ReprType::Wireframe))
            out << "show lines, " << name << "\n";
        if (obj->reprVisible(ReprType::BallStick))
            out << "show sticks, " << name << "\n";
        if (obj->reprVisible(ReprType::Spacefill))
            out << "show spheres, " << name << "\n";
        if (obj->reprVisible(ReprType::Cartoon) || obj->reprVisible(ReprType::Ribbon))
            out << "show cartoon, " << name << "\n";
        if (obj->reprVisible(ReprType::Backbone)) {
            out << "# backbone trace approximated as cartoon\n";
            out << "show cartoon, " << name << " and name CA+C+N+O\n";
        }

        // Color scheme (match MolTerm's CPK palette exactly)
        switch (obj->colorScheme()) {
            case ColorScheme::Element:
                out << "color green, " << name << " and elem C\n";
                out << "color blue, " << name << " and elem N\n";
                out << "color red, " << name << " and elem O\n";
                out << "color yellow, " << name << " and elem S\n";
                out << "color magenta, " << name << " and elem P\n";
                out << "color white, " << name << " and elem H\n";
                out << "color cyan, " << name << " and elem Fe\n";
                out << "color white, " << name << " and not (elem C+N+O+S+P+H+Fe)\n";
                break;
            case ColorScheme::Chain: {
                // Match MolTerm's chain color cycle: A=green, B=cyan, C=magenta, D=yellow, E=red, F=blue
                static const char* kChainColors[] = {"green", "cyan", "magenta", "yellow", "red", "blue"};
                // Collect unique chain IDs
                std::set<std::string> chains;
                for (const auto& a : obj->atoms()) chains.insert(a.chainId);
                for (const auto& ch : chains) {
                    int idx = ch.empty() ? 0 : ((ch[0] - 'A') % 6);
                    if (idx < 0) idx = 0;
                    out << "color " << kChainColors[idx] << ", " << name << " and chain " << ch << "\n";
                }
                break;
            }
            case ColorScheme::SecondaryStructure:
                out << "color red, " << name << " and ss H\n";
                out << "color yellow, " << name << " and ss S\n";
                out << "color green, " << name << " and ss L+''\n";
                break;
            case ColorScheme::BFactor:
                out << "spectrum b, blue_green_red, " << name << "\n";
                break;
            case ColorScheme::PLDDT:
                out << "# pLDDT confidence coloring (AlphaFold)\n";
                out << "color 0x0053D6, " << name << " and b > 90  # very high\n";
                out << "color 0x65CBF3, " << name << " and b > 70 and b <= 90  # high\n";
                out << "color 0xFFDB13, " << name << " and b > 50 and b <= 70  # low\n";
                out << "color 0xFF7D45, " << name << " and b <= 50  # very low\n";
                break;
            case ColorScheme::Rainbow:
                out << "spectrum count, blue_cyan_green_yellow_red, " << name << "\n";
                break;
            default:
                break;
        }

        // Per-atom color overrides
        const auto& atomColors = obj->atomColors();
        if (!atomColors.empty()) {
            std::unordered_map<int, std::vector<int>> colorGroups;
            for (int i = 0; i < static_cast<int>(atomColors.size()); ++i) {
                if (atomColors[i] >= 0) {
                    colorGroups[atomColors[i]].push_back(i);
                }
            }
            for (const auto& [colorPair, indices] : colorGroups) {
                std::string pymolColor = pymolColorName(colorPair);
                if (pymolColor.empty()) continue;
                out << "color " << pymolColor << ", " << name << " and (";
                for (size_t i = 0; i < indices.size() && i < 50; ++i) {
                    if (i > 0) out << " or ";
                    out << "id " << (indices[i] + 1);  // PDB serials are 1-based
                }
                if (indices.size() > 50) out << " or ...";
                out << ")\n";
            }
        }
    }

    out << "\n";

    // Camera / set_view
    // PyMOL set_view 18-float format:
    //   [0-8]:   column-major 3x3 rotation (model axes → camera axes)
    //   [9-11]:  origin of rotation relative to camera (in camera space)
    //   [12-14]: origin of rotation (in model space)
    //   [15]:    front plane distance from camera
    //   [16]:    rear plane distance from camera
    //   [17]:    orthoscopic flag
    //
    // MolTerm's rot_ is row-major 3x3: R*v = [r0 r1 r2; r3 r4 r5; r6 r7 r8] * v
    // PyMOL reads [0-8] as column-major via glm::make_mat4, so:
    //   set_view col j = (view[3j], view[3j+1], view[3j+2])
    // For same rotation, column-major storage = transposed row-major array.
    const auto& cam = tab.camera();
    const auto& r = cam.rotation();
    float cx = cam.centerX(), cy = cam.centerY(), cz = cam.centerZ();

    // PyMOL ortho zoom is controlled by internal Scale (not set_view distance).
    // set_view does NOT touch Scale. So:
    //   1. "zoom" sets Scale to fit all objects → correct zoom level
    //   2. "set_view" then overrides rotation/origin/clipping, leaving Scale intact
    out << "set orthoscopic, 1\n";
    out << "zoom\n";

    // Now apply rotation and origin via set_view.
    // Distance/clipping are generous — Scale (from zoom above) controls actual zoom.
    float dist = 200.0f;

    char buf[1024];
    snprintf(buf, sizeof(buf),
        "set_view (\\\n"
        "  %14.9f, %14.9f, %14.9f,\\\n"
        "  %14.9f, %14.9f, %14.9f,\\\n"
        "  %14.9f, %14.9f, %14.9f,\\\n"
        "  %14.9f, %14.9f, %14.9f,\\\n"
        "  %14.9f, %14.9f, %14.9f,\\\n"
        "  %14.9f, %14.9f, %14.9f )\n",
        r[0], r[3], r[6],
        r[1], r[4], r[7],
        r[2], r[5], r[8],
        0.0f, 0.0f, -dist,
        cx,   cy,    cz,
        50.0f, 500.0f, -1.0f);  // -1 = ortho ON
    out << buf;

    out.close();

    int nObj = static_cast<int>(tab.objects().size());
    return "Exported " + std::to_string(nObj) + " object(s) + .pml to " + dir + "/";
}

std::string SessionExporter::pymolReprName(ReprType r) {
    switch (r) {
        case ReprType::Wireframe: return "lines";
        case ReprType::BallStick: return "sticks";
        case ReprType::Spacefill: return "spheres";
        case ReprType::Cartoon:   return "cartoon";
        case ReprType::Ribbon:    return "ribbon";
        case ReprType::Backbone:  return "cartoon";
    }
    return "lines";
}

std::string SessionExporter::pymolColorScheme(ColorScheme s) {
    switch (s) {
        case ColorScheme::Element:            return "element";
        case ColorScheme::Chain:              return "chain";
        case ColorScheme::SecondaryStructure: return "ss";
        case ColorScheme::BFactor:            return "b";
        case ColorScheme::PLDDT:              return "b";
        default:                              return "";
    }
}

std::string SessionExporter::pymolColorName(int colorPairId) {
    switch (colorPairId) {
        case kColorRed:     return "red";
        case kColorGreen:   return "green";
        case kColorBlue:    return "blue";
        case kColorYellow:  return "yellow";
        case kColorMagenta: return "magenta";
        case kColorCyan:    return "cyan";
        case kColorWhite:   return "white";
        case kColorOrange:  return "orange";
        case kColorPink:    return "hotpink";
        case kColorLime:    return "lime";
        case kColorTeal:    return "teal";
        case kColorPurple:  return "purple";
        case kColorSalmon:  return "salmon";
        case kColorSlate:   return "slate";
        case kColorGray:    return "gray";
        default:            return "";
    }
}

} // namespace molterm
